export const SET_LOCATION_SELECTED = 'SET_LOCATION_SELECTED';
export const GET_LOCATION_CONDITIONS = 'GET_LOCATION_CONDITIONS';
export const GET_LOCATION_CONDITIONS_SUCCESS =
  'GET_LOCATION_CONDITIONS_SUCCESS';
export const GET_LOCATION_CONDITIONS_ERROR = 'GET_LOCATION_CONDITIONS_ERROR';
export const GET_FORECAST = 'GET_FORECAST';
export const GET_FORECAST_SUCCESS = 'GET_FORECAST_SUCCESS';
export const GET_FORECAST_ERROR = 'GET_FORECAST_ERROR';
